### ISSUE TITLE
Can't use my Entity KEY 

### ISSUE THREAD

**Issue by bmbariah** [keng42/facebook-conceal-nodejs#1]
Hello, I have an android app that encrypts some data with facebook conceal 2.0, and I'm trying to use your lib to decrypt it.

How do I pass my Entity key? Entity.create("RANDOMGENERATEDKEY") --java
What do you mean by "myKey should be : 32 bytes with ${encoding} encoded string"?

I tried Buffer.from("RANDOMGENERATEDKEY").toString('base64") but it didn't work

**Comment by keng42** [comment]
'myKey' is a string like '7At16p/dyonmDW3ll9Pl1bmCsWEACxaIzLmyC0ZWGaE='

Buffer(myKey, 'base64').length === 32

**Comment by bmbariah** [comment]
Ok. Thanks. I get it now. Facebook recommends every Entity key be different for every file encrypted. 
How can I force my random generated strings when base64'd to always be 32bytes?

**Comment by bmbariah** [comment]
Nevermind. I've been looking at it all wrong. The first value is the Entity value and the second the CONSTANT 32byte KEY.
lol!
